Repository jupyter-robotics/jupyterlab-urdf, pull requests merged in 2022-07, with the labels that each got.

#3 Automated Changelog Entry for 0.1.0a0 on main
  CHANGELOG.md
Labels: documentation

#7 Use jupyterlab
  docs/conf.py
  docs/index.rst
  docs/jupyterlite_config.json
  docs/notebook.ipynb
Labels: documentation, enhancement

#5 Update installation instructions
  docs/examples.md
  docs/installation.md
Labels: documentation

#6 Configure JupyterLite
  MANIFEST.in
  docs/conf.py
  docs/index.rst
  docs/jupyter-lite.json
  docs/jupyterlite_config.json
  docs/robot.urdf
Labels: documentation, enhancement

#13 Update README to include JupyterLite
  README.md
Labels: documentation

#14 Reload robot once error in XML file is cleared
  src/layout.ts
Labels: bug

#15 Automated Changelog Entry for 0.1.1 on main
  CHANGELOG.md
Labels: documentation

#17 Fix movement for undefined limits
  src/layout.ts
Labels: bug

#18 Automated Changelog Entry for 0.1.2 on main
  CHANGELOG.md
Labels: documentation
