Repository jupyter-robotics/jupyterlab-urdf, pull requests merged in 2025-05, with the labels that each got.

#81 Issue controls panel UI
  src/controls.ts
  style/base.css
Labels: bug, enhancement

#85 Fixes #39 Scene lighting needs improvement
  examples/franka_panda_description/meshes/visual/link0.dae
  src/controls.ts
  src/layout.ts
  src/renderer.ts
  style/base.css
Labels: bug, enhancement

#86 Update update-integration-tests.yml
  .github/workflows/update-integration-tests.yml
Labels: enhancement, ci

#87 Enhancement jupiterlab build.yml
  .github/workflows/build.yml
Labels: enhancement, ci

#88 Increase motion resolution
  src/controls.ts
  src/layout.ts
Labels: enhancement

#89 Update workflows
  .github/workflows/build.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/publish-self-release.yml
  ui-tests/package.json
  ui-tests/yarn.lock
Labels: maintenance, workflows, ci

#90 Update urdf version in docs
  docs/jupyterlite_config.json
Labels: documentation
